version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - 8025:8025

  base: &base
    build: .

  web:
    << : *base
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    depends_on:
      - db
      - mailhog

  test:
    << : *base
    command: pytest
